= Gameplay

For this game jam, our goal is to work primarly on the gameplay, developping it and making it fun
and enjoyable. To do that, we decide to sacrifice the game naration and history to have more time
to spend on the gameplay loop, actions and diversity.

[#gameplay-loop]
== Gameplay loop

In VirusMania, gameplay loop can be read in two level. The first one being the gobal
game loop, that is compose of two main phases. "Breif" gathering and "Breif execution".

VirusMania run around the notion of a breif, witch can be think of as a mission. The governement
that capture you, gives you breif, that represent the next virus that you will need to create.
Each breif contains all the informations that you will need to acomplish the virus creation.
Breif are progressively less indicative of what you will have to do in the execution phase.

[#breif]
== Breif

As explained on the above section, a breif will be gived to you when you start a new mission.
The breif is compose of n section :

1. The goal
2. The tools
3. The delay
4. The ressources

[#breif-the-goal]
=== The goal

The goal section in the breif is a compose of a small text and all the expected effects on the
human body.

[#breif-the-tools]
=== The tools

The tools is a section with a list of all the tools you will need in your lab.

[#breif-the-delay]
=== The delay

Simply the amount of time you have to create the virus

[#breif-the-ressources]
=== The ressources

A non exaustive list of all the ressources you will need.
